# -*- coding: utf-8 -*-
"""車床.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JVno4yex3k1tqM4I1mvqm-m9ZSGoL5PA
"""

# ==================== 自動處理「TRAIN 0-5」資料夾 ====================

from pathlib import Path
import pandas as pd

# 1. 掛載 Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. 設定您的資料夾路徑（請確認路徑正確）
TRAIN_FOLDER = "/content/drive/MyDrive//Time-LLM-main/TRAIN 0-5"

# 3. 自動掃描資料夾內所有 CSV 並合併成 train.csv
csv_files = list(Path(TRAIN_FOLDER).glob("*.csv"))

print(f"找到 {len(csv_files)} 個 CSV 檔案（資料夾：TRAIN 0-5）")

df_list = []
for file in csv_files:
    df = pd.read_csv(file)
    # 只保留需要的兩欄（您可以自行增加其他欄位）
    if 'disp_x_diff' in df.columns and 'disp_z_diff' in df.columns:
        df = df[['disp_x_diff', 'disp_z_diff']]
        df_list.append(df)
    else:
        print(f"警告：檔案 {file.name} 缺少 disp_x_diff 或 disp_z_diff 欄位，已跳過")

# 合併並儲存
train_df = pd.concat(df_list, ignore_index=True)
train_df.to_csv("/content/drive/MyDrive/train.csv", index=False)

print(f"✅ 合併完成！共 {len(train_df)} 筆資料，已儲存為 train.csv")
print(f"train.csv 路徑：/content/drive/MyDrive/train.csv")

from huggingface_hub import login

# 執行這段後，下方會出現一個對話框，請貼上你的 Hugging Face Access Token
login()

# ==================== Time-LLM + ACE 訓練  ====================

!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -q transformers accelerate bitsandbytes

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import numpy as np
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
from google.colab import drive

drive.mount('/content/drive')

# ====================== ACE + Time-LLM 模型 ======================
class ACE_Playbook:
    def __init__(self):
        self.playbook = []
    def generator(self, trend, top5_lags, expert_knowledge):
        return f"[ACE 動態上下文]\n趨勢：{trend}\n前五大滯後：{top5_lags}\n專家知識：{expert_knowledge}\n建議：溫度與壓力對位移影響大。"
    def curator(self, new_strategy):
        self.playbook.append(new_strategy)
        return self.playbook[-3:]

class TimeLLMWithACE(nn.Module):
    def __init__(self, V_prime=200):
        super().__init__()

        bnb_config = BitsAndBytesConfig(load_in_8bit=True)

        self.llm = AutoModelForCausalLM.from_pretrained(
            "meta-llama/Llama-2-7b-hf",
            torch_dtype=torch.float16,
            device_map="auto",
            quantization_config=bnb_config
        )
        self.tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
        self.llm.eval()

        # 凍結 LLM 參數
        for param in self.llm.parameters():
            param.requires_grad = False

        # 【修改 1】自定義層保持預設的 float32，獲得最大的數值穩定空間
        self.patch_embedding = nn.Linear(2, V_prime)
        self.W = nn.Parameter(torch.empty(V_prime, self.llm.config.vocab_size))
        nn.init.xavier_uniform_(self.W)

        # 【核心修正 2】加入 LayerNorm，強制穩定進入 LLM 前的數值尺度
        self.reprogram_norm = nn.LayerNorm(self.llm.config.hidden_size)

        self.output_projection = nn.Linear(self.llm.config.hidden_size, 2)

        self.ace = ACE_Playbook()

    def forward(self, patches, trend, top5_lags, expert_knowledge):
        new_strategy = self.ace.generator(trend, top5_lags, expert_knowledge)
        self.ace.curator(new_strategy)

        prompt = f"[ACE 動態上下文]\n{new_strategy}\n請預測下一個時間步的位移變化。"
        batch_size = patches.shape[0]

        # 此時 patches 預設是 float32
        patch_emb = self.patch_embedding(patches)

        # 提取 LLM 的 Embedding 權重並轉為 float32 進行安全相乘
        llm_weight_fp32 = self.llm.get_input_embeddings().weight.to(torch.float32)
        E_prime = torch.matmul(self.W, llm_weight_fp32)

        # 取得重編程特徵 (float32)
        reprogrammed = torch.matmul(patch_emb, E_prime)

        # 【核心修正 3】套用 LayerNorm，將數值壓縮至安全範圍
        reprogrammed = self.reprogram_norm(reprogrammed)

        # 【修改 4】直到進入 LLM 的最後一刻，才將特徵降級為 float16
        reprogrammed = reprogrammed.to(torch.float16)

        inputs = self.tokenizer(prompt, return_tensors="pt").to(patch_emb.device)
        text_emb = self.llm.get_input_embeddings()(inputs.input_ids)
        text_emb = text_emb.expand(batch_size, -1, -1)

        inputs_embeds = torch.cat([reprogrammed, text_emb], dim=1)

        outputs = self.llm(inputs_embeds=inputs_embeds, output_hidden_states=True)

        hidden = outputs.hidden_states[-1]
        flat = hidden.mean(dim=1)

        # 轉回 float32 進行投影與 Loss 計算
        flat_fp32 = flat.to(torch.float32)
        return self.output_projection(flat_fp32)

class LatheDataset(Dataset):
    def __init__(self, csv_path):
        self.df = pd.read_csv(csv_path)
        # 提取原始數值
        raw_data = torch.tensor(self.df[['disp_x_diff', 'disp_z_diff']].values, dtype=torch.float32)

        # 進行 Z-Score 正規化
        self.mean = raw_data.mean(dim=0)
        self.std = raw_data.std(dim=0)
        # 加上 1e-8 避免除以零的錯誤
        self.data = (raw_data - self.mean) / (self.std + 1e-8)

        self.seq_len = 16

    def __len__(self):
        return len(self.data) - self.seq_len + 1

    def __getitem__(self, idx):
        return self.data[idx : idx + self.seq_len]

# ====================== 訓練 ======================
def train():
    model = TimeLLMWithACE().cuda()
    # 修改 1：調降學習率至 1e-4
    optimizer = optim.Adam([p for p in model.parameters() if p.requires_grad], lr=1e-4)

    train_loader = DataLoader(LatheDataset("/content/drive/MyDrive/train.csv"), batch_size=4, shuffle=True)

    print("開始訓練...")
    for epoch in range(20):
        model.train()
        total_loss = 0
        for batch in train_loader:
            optimizer.zero_grad()
            trend = "upward" if batch.mean() > 0 else "downward"
            top5_lags = [1, 2, 3, 4, 5]
            expert = "車床位移受溫度與壓力影響顯著"

            pred = model(batch.cuda(), trend, top5_lags, expert)

            # 取最後一個時間步作為真實值
            target = batch[:, -1, :].cuda()
            loss = nn.MSELoss()(pred, target)

            loss.backward()

            # 修改 2：加入梯度裁剪，限制最大梯度為 1.0
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

            optimizer.step()
            total_loss += loss.item()

        print(f"Epoch {epoch+1:2d} | Loss: {total_loss/len(train_loader):.4f}")

    torch.save(model.state_dict(), "/content/drive/MyDrive/time_llm_ace_144cu.pth")
    print("訓練完成，模型已儲存。")


train()

# ==================== 自動處理「測試集」資料夾 ====================

from pathlib import Path
import pandas as pd
from google.colab import drive

# 1. 掛載 Google Drive (如果您剛剛已經掛載過，這步會自動略過)
drive.mount('/content/drive')

# 2. 設定您的「測試集」資料夾路徑
# ⚠️ 注意：請將最後面的 "TEST_FOLDER_NAME" 換成您實際放測試資料的資料夾名稱！
TEST_FOLDER = "/content/drive/MyDrive/Time-LLM-main/TEST 0-5"

# 3. 自動掃描資料夾內所有 CSV 並合併成 test.csv
csv_files = list(Path(TEST_FOLDER).glob("*.csv"))

print(f"🔍 準備掃描資料夾：{TEST_FOLDER}")
print(f"📂 共找到 {len(csv_files)} 個 CSV 檔案")

df_list = []
for file in csv_files:
    df = pd.read_csv(file)
    # 只保留需要的兩欄
    if 'disp_x_diff' in df.columns and 'disp_z_diff' in df.columns:
        df = df[['disp_x_diff', 'disp_z_diff']]
        df_list.append(df)
    else:
        print(f"⚠️ 警告：檔案 {file.name} 缺少 disp_x_diff 或 disp_z_diff 欄位，已跳過")

# 4. 合併並儲存
if len(df_list) > 0:
    test_df = pd.concat(df_list, ignore_index=True)
    test_df.to_csv("/content/drive/MyDrive/test.csv", index=False)
    print(f"✅ 測試集合併完成！共收集了 {len(test_df)} 筆資料。")
    print(f"💾 test.csv 已經成功儲存至：/content/drive/MyDrive/test.csv")
else:
    print("❌ 錯誤：找不到任何有效的 CSV 檔案，無法建立 test.csv。請確認您的資料夾路徑是否正確！")

!pip install -q transformers accelerate "bitsandbytes>=0.46.
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
!pip install -q transformers accelerate bitsandbytes

import pandas as pd

# 讀取測試集
test_file_path = "/content/drive/MyDrive/test.csv"
df = pd.read_csv(test_file_path)

print(f"🧹 清理前資料筆數: {len(df)}")

# 強制將欄位轉為數值格式，如果遇到無法轉換的文字就變成 NaN
df['disp_x_diff'] = pd.to_numeric(df['disp_x_diff'], errors='coerce')
df['disp_z_diff'] = pd.to_numeric(df['disp_z_diff'], errors='coerce')

# 刪除所有包含 NaN (空值或壞資料) 的列
df_clean = df.dropna()

print(f"✨ 清理後資料筆數: {len(df_clean)}")
print(f"🗑️ 共剔除了 {len(df) - len(df_clean)} 筆異常資料")

# 覆蓋儲存回原本的檔案
df_clean.to_csv(test_file_path, index=False)
print("✅ 測試集清理完成！")

import torch
import torch.nn as nn
import matplotlib.pyplot as plt
import pandas as pd
from torch.utils.data import Dataset, DataLoader
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
import numpy as np
from google.colab import drive

# ================= 1. 定義依賴的類別 =================

class ACE_Playbook:
    def __init__(self):
        self.playbook = []
    def generator(self, trend, top5_lags, expert_knowledge):
        return f"[ACE 動態上下文]\n趨勢：{trend}\n前五大滯後：{top5_lags}\n專家知識：{expert_knowledge}\n建議：溫度與壓力對位移影響大。"
    def curator(self, new_strategy):
        self.playbook.append(new_strategy)
        return self.playbook[-3:]

class TimeLLMWithACE(nn.Module):
    def __init__(self, V_prime=200):
        super().__init__()
        bnb_config = BitsAndBytesConfig(load_in_8bit=True)
        self.llm = AutoModelForCausalLM.from_pretrained(
            "meta-llama/Llama-2-7b-hf",
            torch_dtype=torch.float16,
            device_map="auto",
            quantization_config=bnb_config
        )
        self.tokenizer = AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-hf")
        self.llm.eval()

        for param in self.llm.parameters():
            param.requires_grad = False

        self.patch_embedding = nn.Linear(2, V_prime)
        self.W = nn.Parameter(torch.empty(V_prime, self.llm.config.vocab_size))
        nn.init.xavier_uniform_(self.W)
        self.reprogram_norm = nn.LayerNorm(self.llm.config.hidden_size)
        self.output_projection = nn.Linear(self.llm.config.hidden_size, 2)
        self.ace = ACE_Playbook()

    def forward(self, patches, trend, top5_lags, expert_knowledge):
        new_strategy = self.ace.generator(trend, top5_lags, expert_knowledge)
        self.ace.curator(new_strategy)
        prompt = f"[ACE 動態上下文]\n{new_strategy}\n請預測下一個時間步的位移變化。"
        batch_size = patches.shape[0]

        patch_emb = self.patch_embedding(patches)
        llm_weight_fp32 = self.llm.get_input_embeddings().weight.to(torch.float32)
        E_prime = torch.matmul(self.W, llm_weight_fp32)
        reprogrammed = torch.matmul(patch_emb, E_prime)
        reprogrammed = self.reprogram_norm(reprogrammed).to(torch.float16)

        inputs = self.tokenizer(prompt, return_tensors="pt").to(patch_emb.device)
        text_emb = self.llm.get_input_embeddings()(inputs.input_ids)
        text_emb = text_emb.expand(batch_size, -1, -1)

        inputs_embeds = torch.cat([reprogrammed, text_emb], dim=1)
        outputs = self.llm(inputs_embeds=inputs_embeds, output_hidden_states=True)

        hidden = outputs.hidden_states[-1]
        flat = hidden.mean(dim=1)
        return self.output_projection(flat.to(torch.float32))

class LatheDataset(Dataset):
    def __init__(self, csv_path, train_mean=None, train_std=None):
        self.df = pd.read_csv(csv_path)
        raw_data = torch.tensor(self.df[['disp_x_diff', 'disp_z_diff']].values, dtype=torch.float32)
        if train_mean is None or train_std is None:
            self.mean = raw_data.mean(dim=0)
            self.std = raw_data.std(dim=0)
        else:
            self.mean = train_mean
            self.std = train_std
        self.data = (raw_data - self.mean) / (self.std + 1e-8)
        self.seq_len = 16
    def __len__(self):
        return len(self.data) - self.seq_len + 1
    def __getitem__(self, idx):
        return self.data[idx : idx + self.seq_len]

# ================= 2. 測試與繪圖流程 =================

def run_test_evaluation():
    print("🔄 準備載入模型與測試資料...")
    model = TimeLLMWithACE().cuda()
    model.load_state_dict(torch.load("/content/drive/MyDrive//Time-LLM-main/time_llm_ace_144cu.pth"))
    model.eval()

    # 取出 train.csv 的正規化參數給 test.csv 用
    train_dataset = LatheDataset("/content/drive/MyDrive/train.csv")
    test_dataset = LatheDataset("/content/drive/MyDrive/test.csv",
                                train_mean=train_dataset.mean,
                                train_std=train_dataset.std)
    test_loader = DataLoader(test_dataset, batch_size=4, shuffle=False)

    print(" 開始進行測試集推論...")
    total_test_loss = 0
    actuals_x, preds_x = [], []

    with torch.no_grad():
        for batch in test_loader:
            trend = "upward" if batch.mean() > 0 else "downward"
            top5_lags = [1, 2, 3, 4, 5]
            expert = "車床位移受溫度與壓力影響顯著"

            pred = model(batch.cuda(), trend, top5_lags, expert)
            target = batch[:, -1, :].cuda()

            loss = nn.MSELoss()(pred, target)
            total_test_loss += loss.item()

            std_x = train_dataset.std[0].item()
            mean_x = train_dataset.mean[0].item()

            for i in range(pred.shape[0]):
                real_x = target[i][0].item() * std_x + mean_x
                pred_x = pred[i][0].item() * std_x + mean_x
                actuals_x.append(real_x)
                preds_x.append(pred_x)

    avg_test_loss = total_test_loss / len(test_loader)
    print("="*40)
    print(f"🎯 測試集總結 (Test Evaluation)")
    print(f"✅ Average Test Loss (MSE): {avg_test_loss:.4f}")
    print("="*40)

    # 繪圖
    plot_limit = min(150, len(actuals_x))
    plt.figure(figsize=(14, 6))
    plt.plot(actuals_x[:plot_limit], label="Actual X-Axis Displacement", color='#1f77b4', linewidth=2)
    plt.plot(preds_x[:plot_limit], label="Predicted X-Axis Displacement", color='#ff7f0e', linestyle='--', linewidth=2)
    plt.title("Time-LLM + ACE: Test Set Predictions (X-Axis)", fontsize=16)
    plt.xlabel("Time Steps", fontsize=12)
    plt.ylabel("Displacement Difference (Real Units)", fontsize=12)
    plt.legend(fontsize=12)
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.show()

# 執行
run_test_evaluation()

import torch
import pandas as pd

# ==========================================
# 實戰預測工具 (修正資料型態版本)
# ==========================================

class LathePredictor:
    def __init__(self, model_path, train_csv_path):
        print("啟動預測引擎中...")
        # 1. 載入模型架構與權重
        self.model = TimeLLMWithACE().cuda()
        self.model.load_state_dict(torch.load(model_path))
        self.model.eval()

        # 2. 載入正規化參數
        train_df = pd.read_csv(train_csv_path)
        raw_data = torch.tensor(train_df[['disp_x_diff', 'disp_z_diff']].values, dtype=torch.float32)
        self.mean = raw_data.mean(dim=0).cuda()
        self.std = raw_data.std(dim=0).cuda()

        print("預測引擎啟動完成，準備接收數據。")

    def predict(self, recent_16_data, expert_knowledge="機台運作正常"):
        """
        輸入:
        1. recent_16_data: 過去 16 個時間步的真實數據
        2. expert_knowledge: 動態上下文提示
        """
        # 1. 轉換為 Tensor (保持 float32)
        if isinstance(recent_16_data, pd.DataFrame):
            input_tensor = torch.tensor(recent_16_data[['disp_x_diff', 'disp_z_diff']].values, dtype=torch.float32).cuda()
        else:
            input_tensor = torch.tensor(recent_16_data, dtype=torch.float32).cuda()

        input_tensor = input_tensor.unsqueeze(0)

        # 2. Z-Score 正規化
        normalized_input = (input_tensor - self.mean) / (self.std + 1e-8)

        # 3. 判斷趨勢
        trend = "upward" if normalized_input.mean() > 0 else "downward"
        top5_lags = [1, 2, 3, 4, 5]

        # 4. 呼叫模型進行預測 (移除 .to(torch.float16)，保持 float32 輸入)
        with torch.no_grad():
            pred = self.model(normalized_input, trend, top5_lags, expert_knowledge)

        # 5. 反標準化回真實位移量
        real_pred = pred[0] * self.std + self.mean

        return real_pred[0].item(), real_pred[1].item()


# ==========================================
# 實際使用範例
# ==========================================

predictor = LathePredictor(
    model_path="/content/drive/MyDrive//Time-LLM-main/time_llm_ace_144cu.pth",
    train_csv_path="/content/drive/MyDrive/train.csv"
)

# 讀取測試集前 16 筆數據模擬即時輸入
test_df = pd.read_csv("/content/drive/MyDrive/test.csv").dropna()
latest_16_steps = test_df.iloc[0:16]

predicted_x, predicted_z = predictor.predict(
    recent_16_data=latest_16_steps,
    expert_knowledge="警告：連續高速切削，刀具溫度急遽上升，注意熱膨脹。"
)

print("-" * 40)
print("預測結果出爐：")
print(f"下一秒 X 軸預測位移差: {predicted_x:.5f} mm")
print(f"下一秒 Z 軸預測位移差: {predicted_z:.5f} mm")
print("-" * 40)

import torch
import pandas as pd

# ==========================================
# 實戰預測工具 (修正資料型態版本)
# ==========================================

class LathePredictor:
    def __init__(self, model_path, train_csv_path):
        print("啟動預測引擎中...")
        # 1. 載入模型架構與權重
        self.model = TimeLLMWithACE().cuda()
        self.model.load_state_dict(torch.load(model_path))
        self.model.eval()

        # 2. 載入正規化參數
        train_df = pd.read_csv(train_csv_path)
        raw_data = torch.tensor(train_df[['disp_x_diff', 'disp_z_diff']].values, dtype=torch.float32)
        self.mean = raw_data.mean(dim=0).cuda()
        self.std = raw_data.std(dim=0).cuda()

        print("預測引擎啟動完成，準備接收數據。")

    def predict(self, recent_16_data, expert_knowledge="機台運作正常"):
        """
        輸入:
        1. recent_16_data: 過去 16 個時間步的真實數據
        2. expert_knowledge: 動態上下文提示
        """
        # 1. 轉換為 Tensor (保持 float32)
        if isinstance(recent_16_data, pd.DataFrame):
            input_tensor = torch.tensor(recent_16_data[['disp_x_diff', 'disp_z_diff']].values, dtype=torch.float32).cuda()
        else:
            input_tensor = torch.tensor(recent_16_data, dtype=torch.float32).cuda()

        input_tensor = input_tensor.unsqueeze(0)

        # 2. Z-Score 正規化
        normalized_input = (input_tensor - self.mean) / (self.std + 1e-8)

        # 3. 判斷趨勢
        trend = "upward" if normalized_input.mean() > 0 else "downward"
        top5_lags = [1, 2, 3, 4, 5]

        # 4. 呼叫模型進行預測 (移除 .to(torch.float16)，保持 float32 輸入)
        with torch.no_grad():
            pred = self.model(normalized_input, trend, top5_lags, expert_knowledge)

        # 5. 反標準化回真實位移量
        real_pred = pred[0] * self.std + self.mean

        return real_pred[0].item(), real_pred[1].item()


# ==========================================
# 實際使用範例
# ==========================================

predictor = LathePredictor(
    model_path="/content/drive/MyDrive//Time-LLM-main/time_llm_ace_144cu.pth",
    train_csv_path="/content/drive/MyDrive/train.csv"
)

# 讀取測試集前 16 筆數據模擬即時輸入
test_df = pd.read_csv("/content/drive/MyDrive/test.csv").dropna()
latest_16_steps = test_df.iloc[0:16]

predicted_x, predicted_z = predictor.predict(
    recent_16_data=latest_16_steps,
    expert_knowledge="機台剛開機，冷卻液充足，溫度極低且極為穩定。"
)

print("-" * 40)
print("預測結果出爐：")
print(f"下一秒 X 軸預測位移差: {predicted_x:.5f} mm")
print(f"下一秒 Z 軸預測位移差: {predicted_z:.5f} mm")
print("-" * 40)